### ISSUE TITLE
working logo?

### ISSUE THREAD

**Issue by andrewMacmurray** [wide-grip/wide-grip#1]
@RobStallion 😉 
<img width="689" alt="screen shot 2018-02-20 at 20 22 08" src="https://user-images.githubusercontent.com/14013616/36447283-d3254370-167b-11e8-9f8d-e16b74583cb9.png">

**Comment by RobStallion** [comment]
OMG!!!!!!!!!!! I LOVE IT ❤️

**Comment by andrewMacmurray** [comment]
![wide-grip](https://user-images.githubusercontent.com/14013616/36733016-43518820-1bc7-11e8-9fae-9504a8a07620.png)

With bar covering thumbs
